### ISSUE TITLE
The npm download Version 16.1.28 doesn't work with Internationalization.

### ISSUE THREAD

**Issue by j-nord** [syncfusion/ej2#25] opened 2018-03-31 08:00 UTC
**The npm download Version 16.1.28 doesn't work with Internationalization.**

When we recovert a older directory (@syncfusion) of Version 16.1.28 from a backup, the Internationalization works. When we install the Version over npm download it doesn't work.

**We searched one day for errors to find out that there is a broken version on the npm server. That's the second time. What's going on there??**

Regards
j.nord

**Comment by bharathm03** [comment] 2018-04-02 05:30
@j-nord We regret for the inconvenience caused. We are unable to reproduce this issue. Can you please share the following information?

1. What is the issue facing like CLDR data not loading/bundling, script errors on browser runtime etc
2. error logs/output such as npm error log file, webpack error logs, stack trace.
3. node.js and npm versions, browser details (if it is runtime error)

This will enable us to understand more about the problem and give proper solution.

Regards,
Bharath

**Comment by j-nord** [comment] 2018-04-03 08:53
Hi Bharath,

the internationalization does not work properly !

Our project.json:

{
 "name": "angular-webpack-visualstudio",
 "version": "1.0.0",
 "description": "An Angular VS template",
 "main": "wwwroot/index.html",
 "author": "",
 "license": "ISC",
 "repository": {
 "type": "git",
 "url": "https://github.com/damienbod/Angular2WebpackVisualStudio.git"
 },
 "scripts": {
 "ngc": "ngc -p ./tsconfig-aot.json",
 "build:dev": "set NODE_ENV=development && webpack",
 "build:prod": "ngc -p ./tsconfig-aot.json && set NODE_ENV=production && webpack",
 "build:dev-p": "set NODE_ENV=development && webpack --progress --color",
 "build:prod-p": "ngc -p ./tsconfig-aot.json && set NODE_ENV=production && webpack --progress --color",
 "publish-for-iis": "npm run build-production && dotnet publish -c Release",
 "test": "karma start"
 },
 "dependencies": {
"@angular/animations": "5.2.9",
"@angular/common": "5.2.9",
"@angular/compiler": "5.2.9",
"@angular/compiler-cli": "5.2.9",
"@angular/core": "5.2.9",
"@angular/forms": "5.2.9",
"@angular/http": "5.1.0",
"@angular/platform-browser": "5.2.9",
"@angular/platform-browser-dynamic": "5.2.9",
"@angular/platform-server": "5.2.9",
"@angular/router": "5.2.9",
"@angular/upgrade": "5.2.9",
"@ng-bootstrap/ng-bootstrap": "1.0.1",
"@syncfusion/ej2-base": "16.1.32",
"@syncfusion/ej2-ng-base": "16.1.32",
"@syncfusion/ej2-ng-buttons": "16.1.32",
"@syncfusion/ej2-ng-calendars": "16.1.32",
"@syncfusion/ej2-ng-dropdowns": "16.1.32",
"@syncfusion/ej2-ng-grids": "16.1.32",
"@syncfusion/ej2-ng-inputs": "16.1.32",
"@syncfusion/ej2-ng-navigations": "16.1.32",
"@syncfusion/ej2-ng-popups": "16.1.32",
"aspnet-webpack": "2.0.3",
"bootstrap": "4.0.0",
"classlist.js": "^1.1.20150312",
"core-js": "2.5.3",
"file-saver": "^1.3.3",
"font-awesome": "4.7.0",
"fs": "0.0.1-security",
"ie-shim": "~0.1.0",
"intl": "^1.2.5",
"jquery": "3.3.1",
"json2csv": "^3.8.1",
"moment": "2.19.4",
"ng2-archwizard": "2.1.0",
"ngx-openlayers": "0.6.10",
"popper.js": "1.12.9",
"reflect-metadata": "0.1.10",
"rxjs": "5.5.5",
"tether": "1.4.0",
"web-animations-js": "^2.3.1",
"webpack-node-externals": "^1.6.0",
"zone.js": "0.8.18"


},
 "devDependencies": {
"@ngtools/webpack": "1.9.0",
"@types/file-saver": "0.0.1",
"@types/jasmine": "2.5.47",
"@types/jquery": "^2.0.45",
"@types/node": "7.0.13",
"angular-router-loader": "0.8.0",
"angular2-template-loader": "0.6.2",
"awesome-typescript-loader": "3.4.1",
"cldr-data": "32.0.1",
"clean-webpack-plugin": "^0.1.16",
"concurrently": "^3.4.0",
"copy-webpack-plugin": "^4.0.1",
"css-loader": "^0.28.0",
"extract-text-webpack-plugin": "3.0.2",
"file-loader": "^0.11.1",
"html-webpack-plugin": "2.30.1",
"jasmine-core": "2.5.2",
"json-loader": "0.5.7",
"node-sass": "^4.5.2",
"raw-loader": "^0.5.1",
"rimraf": "^2.6.1",
"sass-loader": "6.0.6",
"source-map-loader": "0.2.3",
"style-loader": "0.19.0",
"to-string-loader": "1.1.5",
"ts-helpers": "^1.1.2",
"ts-loader": "2.3.7",
"tslint": "^5.1.0",
"tslint-loader": "^3.5.2",
"typescript": "2.5.2",
"url-loader": "^0.5.8",
"webpack": "3.11.0",
"webpack-dev-server": "2.11.1",
"webpack-hot-middleware": "2.21.2",
"webpack-parallel-uglify-plugin": "1.0.2"


}
}

npm version 5.7.1
node version 9.8.0

We get only a polyfill error because we run the program in Chrome Version 65.0.3325.181 (Offizieller Build) (64-Bit)

**It can not be a cldr error because when we only recovery the old @syncfusion directory it runs!**

Regards
j.nord

**Comment by bharathm03** [comment] 2018-04-03 09:16
@j-nord I will try again with your package.json configuration. Meantime, Can you please describe how internationalization does not work properly like formatting not applied, controls are not rendering, any specific control not working etc? Also, please share the [screenshot of polyfill error with stack-trace](https://i.stack.imgur.com/4iLhc.png) that you are facing in chrome.

Regards
Bharath

**Comment by j-nord** [comment] 2018-04-03 11:32
1. All controls not working with german language. **When we only recovery the old @syncfusion directory it runs!**

de.js:1 Uncaught ReferenceError: IntlPolyfill is not defined
    at Object.<anonymous> (de.js:1)
    at __webpack_require__ (bootstrap ebdf26c9724fb32145d5:712)
    at fn (bootstrap ebdf26c9724fb32145d5:117)
    at Object.<anonymous> (process-update.js:146)
    at __webpack_require__ (bootstrap ebdf26c9724fb32145d5:712)
    at fn (bootstrap ebdf26c9724fb32145d5:117)
    at Object.<anonymous> (es6.set.js:14)
    at __webpack_require__ (bootstrap ebdf26c9724fb32145d5:712)
    at bootstrap ebdf26c9724fb32145d5:810
    at bootstrap ebdf26c9724fb32145d5:810

**Comment by bharathm03** [comment] 2018-04-04 10:10
@j-nord Thanks for the information. It turns out to be an issue with package referencing in our angular npm package. To resolve this issue, please add js npm packages as well in your package.json such as ej2-grids, ej2-calendars etc., with same version. 

We will update the full response with complete sample and timeline for the fix asap.

Regards,
Bharath

**Comment by ajithr** [comment] 2018-04-04 13:25
Hi @j-nord ,

We are able to reproduce the issue and the npm dependency references in the Angular npm packages is the cause of the issue. We have logged an issue report for this and the fix for this issue will be available by next patch release (April 10, 2018). 

As of now, we suggest you to use the javascript npm package along with Angular package to resolve the issue

```
    "@syncfusion/ej2": "16.1.28",
    "@syncfusion/ej2-base": "16.1.28",
    "@syncfusion/ej2-ng-base": "16.1.28",
    "@syncfusion/ej2-buttons": "16.1.28",
    "@syncfusion/ej2-calendars": "16.1.28",
    "@syncfusion/ej2-dropdowns": "16.1.28",
    "@syncfusion/ej2-grids": "16.1.28",
    "@syncfusion/ej2-inputs": "16.1.28",
    "@syncfusion/ej2-navigations": "16.1.28",
    "@syncfusion/ej2-popups": "16.1.28",
    "@syncfusion/ej2-ng-buttons": "16.1.28",
    "@syncfusion/ej2-ng-calendars": "16.1.28",
    "@syncfusion/ej2-ng-dropdowns": "16.1.28",
    "@syncfusion/ej2-ng-grids": "16.1.28",
    "@syncfusion/ej2-ng-inputs": "16.1.28",
    "@syncfusion/ej2-ng-navigations": "16.1.28",
    "@syncfusion/ej2-ng-popups": "16.1.28",
````

Please refer the below sample for further details.

https://github.com/jasparvathi/AngularWebpackVisualStudio/

Regards,
Ajith R

**Closed** 2018-07-05 09:17 UTC
Labels: bug
